### ISSUE TITLE
How does this exactly work?

### ISSUE THREAD

**Issue by sandor111** [DonoA/WarLords#1]
How does this exactly work?

**Comment by DonoA** [comment]
It's not meant to be used, its just a little side project I had for a while.

**Comment by sandor111** [comment]
Could you please help me make a plugin?

**Comment by DonoA** [comment]
I'm not really interested in teaching, sorry. That said, when I was first learning http://wiki.bukkit.org/Plugin_Tutorial was a really helpful resource.

**Comment by sandor111** [comment]
Not teaching but just making a plugin for my server :P

**Comment by DonoA** [comment]
If you make a public repo and link it to me I might take a look.

**Comment by sandor111** [comment]
I can't code so..

**Comment by DonoA** [comment]
In that case either learn or dont' bother me again.

**Comment by sandor111** [comment]
I got a server with max 40 people online and i would really like a faction add on which adds a new war system to it

**Comment by sandor111** [comment]
Ok thanks for your time

**Comment by sandor111** [comment]
https://github.com/Axiom1999/WarDeclaration that is the project
